### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by ChrisDeveloping** [levi-turner/QlikSenseScripts#1]
Hey,

when running your script I get the following error:

Invoke-RestMethod : Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung.
In C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\1.13.1\functions\core.ps1:32 Zeichen:15
+ ...   $result = Invoke-RestMethod -Method $method -Uri $path @params -Web ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

The following code leads to the error:
$RESTAppObject = Invoke-QlikGet -path "/qrs/dataconnection/full?filter=(name eq 'monitor_apps_REST_appobject')"

What can I do?

Greetings

**Comment by Nillth** [comment]
@ChrisDeveloping  please update to the latest version of Qlik-cli to resolve the issue
Based on the error 

> Invoke-RestMethod : Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung.
In C:\Program Files\WindowsPowerShell\Modules\Qlik-Cli\1.13.1\functions\core.ps1:32 Zeichen:15

the issues is with the Qlik-Cli module.
the command
> $RESTAppObject = Invoke-QlikGet -path "/qrs/dataconnection/full?filter=(name eq 'monitor_apps_REST_appobject')"

tested on the current Qlik-Cli works correctly

**Comment by levi-turner** [comment]
Closing as old. I did make an update (https://github.com/levi-turner/QlikSenseScripts/blob/master/qs-cli/qs-cli-pwd_change.ps1) which uses a loop rather than the previous hideous statically defined list of data connections.
