### ISSUE TITLE
qlik_sense_purge_unused_user_access_passes.ps1

### ISSUE THREAD

**Issue by LenHoover** [levi-turner/QlikSenseScripts#6]
Hi Levi,

Trust you keeping well.
I'm looking for this script qlik_sense_purge_unused_user_access_passes.ps1 mentioned on the Qlik community site.

Thanks
Regards,
L

**Comment by levi-turner** [comment]
Answered on here: https://github.com/ahaydon/Qlik-Cli-Windows/issues/175

Cheers
