### ISSUE TITLE
Create New Stream on QS programmatically

### ISSUE THREAD

**Issue by LenHoover** [levi-turner/QlikSenseScripts#7]
Hi,

I'm trying to create a new stream on qlik sense and assign the custom property StreamGrp to ABC (which already exists) programmatically via powershell. 

Scenario :

The custom property is called StreamGrp (resource type - Streams) which has values ABC and DEF.
I need to create a new stream called ABC and assign the custom property StreamGrp to ABC  in powershell.

Can you please advise on a solution to achieve this?

Many thanks!

Regards,
Len

**Comment by levi-turner** [comment]
https://github.com/ahaydon/Qlik-Cli-Windows/issues/177
